name: Check Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  install-deps:
    if: github.repository == 'mazipan/login-page-css'
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install locked dependencies
        run: yarn install

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache-deps
        with:
          key: ${{ runner.os }}-yarn-store-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-store-
          path: '.'

  lint:
    if: github.repository == 'mazipan/login-page-css'
    name: Lint
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Restore cached dependencies
        uses: actions/cache@v3
        id: restore-deps
        with:
          key: ${{ runner.os }}-yarn-store-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-store-
          path: '.'

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Lint Code
        run: yarn lint

  build:
    if: github.repository == 'mazipan/login-page-css'
    name: Build
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Restore cached dependencies
        uses: actions/cache@v3
        id: restore-deps
        with:
          key: ${{ runner.os }}-yarn-store-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-store-
          path: '.'

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Build Project
        run: yarn build
